#ifndef __IBLE_UUID__
#define __IBLE_UUID__

#define BT_UUID_GAP                       0x1800
#define BT_UUID_GATT                      0x1801
#define BT_UUID_CTS                       0x1805
#define BT_UUID_DIS                       0x180a
#define BT_UUID_HRS                       0x180d
#define BT_UUID_BAS                       0x180f
#define BT_UUID_HIDS                      0x1812
#define BT_UUID_CSC                       0x1816
#define BT_UUID_ESS                       0x181a
#define BT_UUID_IPSS                      0x1820
#define BT_UUID_GATT_PRIMARY              0x2800
#define BT_UUID_GATT_SECONDARY            0x2801
#define BT_UUID_GATT_INCLUDE              0x2802
#define BT_UUID_GATT_CHRC                 0x2803
#define BT_UUID_GATT_CEP                  0x2900
#define BT_UUID_GATT_CUD                  0x2901
#define BT_UUID_GATT_CCC                  0x2902
#define BT_UUID_GATT_SCC                  0x2903
#define BT_UUID_GATT_CPF                  0x2904
#define BT_UUID_VALID_RANGE               0x2906
#define BT_UUID_HIDS_EXT_REPORT           0x2907
#define BT_UUID_HIDS_REPORT_REF           0x2908
#define BT_UUID_ES_CONFIGURATION          0x290b
#define BT_UUID_ES_MEASUREMENT            0x290c
#define BT_UUID_ES_TRIGGER_SETTING        0x290d
#define BT_UUID_GAP_DEVICE_NAME           0x2a00
#define BT_UUID_GAP_APPEARANCE            0x2a01
#define BT_UUID_GAP_PPCP                  0x2a04
#define BT_UUID_GATT_SC                   0x2a05
#define BT_UUID_BAS_BATTERY_LEVEL         0x2a19
#define BT_UUID_DIS_SYSTEM_ID             0x2a23
#define BT_UUID_DIS_MODEL_NUMBER          0x2a24
#define BT_UUID_DIS_SERIAL_NUMBER         0x2a25
#define BT_UUID_DIS_FIRMWARE_REVISION     0x2a26
#define BT_UUID_DIS_HARDWARE_REVISION     0x2a27
#define BT_UUID_DIS_SOFTWARE_REVISION     0x2a28
#define BT_UUID_DIS_MANUFACTURER_NAME     0x2a29
#define BT_UUID_DIS_PNP_ID                0x2a50
#define BT_UUID_CTS_CURRENT_TIME          0x2a2b
#define BT_UUID_MAGN_DECLINATION          0x2a2c
#define BT_UUID_HRS_MEASUREMENT           0x2a37
#define BT_UUID_HRS_BODY_SENSOR           0x2a38
#define BT_UUID_HRS_CONTROL_POINT         0x2a39
#define BT_UUID_HIDS_INFO                 0x2a4a
#define BT_UUID_HIDS_REPORT_MAP           0x2a4b
#define BT_UUID_HIDS_CTRL_POINT           0x2a4c
#define BT_UUID_HIDS_REPORT               0x2a4d
#define BT_UUID_CSC_MEASUREMENT           0x2a5b
#define BT_UUID_CSC_FEATURE               0x2a5c
#define BT_UUID_SENSOR_LOCATION           0x2a5d
#define BT_UUID_SC_CONTROL_POINT          0x2a55
#define BT_UUID_ELEVATION                 0x2a6c
#define BT_UUID_PRESSURE                  0x2a6d
#define BT_UUID_TEMPERATURE               0x2a6e
#define BT_UUID_HUMIDITY                  0x2a6f
#define BT_UUID_TRUE_WIND_SPEED           0x2a70
#define BT_UUID_TRUE_WIND_DIR             0x2a71
#define BT_UUID_APPARENT_WIND_SPEED       0x2a72
#define BT_UUID_APPARENT_WIND_DIR         0x2a73
#define BT_UUID_GUST_FACTOR               0x2a74
#define BT_UUID_POLLEN_CONCENTRATION      0x2a75
#define BT_UUID_UV_INDEX                  0x2a76
#define BT_UUID_IRRADIANCE                0x2a77
#define BT_UUID_RAINFALL                  0x2a78
#define BT_UUID_WIND_CHILL                0x2a79
#define BT_UUID_HEAT_INDEX                0x2a7a
#define BT_UUID_DEW_POINT                 0x2a7b
#define BT_UUID_DESC_VALUE_CHANGED        0x2a7d
#define BT_UUID_MAGN_FLUX_DENSITY_2D      0x2aa0
#define BT_UUID_MAGN_FLUX_DENSITY_3D      0x2aa1
#define BT_UUID_BAR_PRESSURE_TREND        0x2aa3

/*
 * Protocol UUIDs
 */
#define BT_UUID_SDP                       0x0001
#define BT_UUID_UDP                       0x0002
#define BT_UUID_RFCOMM                    0x0003
#define BT_UUID_TCP                       0x0004
#define BT_UUID_TCS_BIN                   0x0005
#define BT_UUID_TCS_AT                    0x0006
#define BT_UUID_ATT                       0x0007
#define BT_UUID_OBEX                      0x0008
#define BT_UUID_IP                        0x0009
#define BT_UUID_FTP                       0x000a
#define BT_UUID_HTTP                      0x000c
#define BT_UUID_BNEP                      0x000f
#define BT_UUID_UPNP                      0x0010
#define BT_UUID_HIDP                      0x0011
#define BT_UUID_HCRP_CTRL                 0x0012
#define BT_UUID_HCRP_DATA                 0x0014
#define BT_UUID_HCRP_NOTE                 0x0016
#define BT_UUID_AVCTP                     0x0017
#define BT_UUID_AVDTP                     0x0019
#define BT_UUID_CMTP                      0x001b
#define BT_UUID_UDI                       0x001d
#define BT_UUID_MCAP_CTRL                 0x001e
#define BT_UUID_MCAP_DATA                 0x001f
#define BT_UUID_L2CAP                     0x0100

#endif  // __IBLE_UUID__
