#ifndef __SWG_H__
#define __SWG_H__

/**
 * @brief Square wave generator (SWG) Driver, compoenent used AD9837
 * @{
 */

#include "../configuration.h"

/**
 * @brief SWG maximum frequency which can be surely handle
 *
 */
#define FREQUENCY_MAX     100000

/**
 * @brief initialize the square wave generator driver
 *
 * @param[in] frequency					initial frequency
 *
 * The square signal start being generated afeter the initialization
 */
void swg_init(float frequency);

/**
 * @brief change the frequency of the signal generated by SWG driver
 *
 * @param[in] frequency					new frequency
 *
 */
void swg_set_frequency(float frequency);

/**
 * @brief SWG driver stop generating a signal
 *
 */
void swg_sleep();

/**
 * @brief SWG driver restart generating a signal
 *
 * The frequency of the signal is the same than the signal before sleeping
 */
void swg_wakeup();

/**
 * @brief test if the driver is sleeping
 * @return	true if the driver is sleeping
 *
 */
bool swg_isSleeping();

/**
 * @}
 */

#endif  // __SWG_H__
